generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Bug
    theme:            default
    
    fields:
      id_utente: 	{name: Utente}
      data: 		{name: Data Ins., params: date_format='dd/MM/yyyy'}
      
    list:
      title: Lista Bug
      display: [id, username, priorita, modulo, data, stato]
      filters:	[_priorita, _modulo, _stato, id_utente]
      
    edit:
      title: Modifica Bug
      display: 
        "Utente": [username, data]
        "Bug": [_prioritaList, _moduloList, _statoList, testo]
      fields: 
        priorita_list: {name: Priorita}
        modulo_list: {name: Modulo}
        stato_list: {name: Stato}
        username: { type: plain}
        data: {type: plain}
        testo: {params: size=50x10}