prod:
  .settings:
    logging_enabled: false
    no_script_name:           false

dev:
  .settings:
    # E_ALL | E_STRICT = 4095
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    stats:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    # E_ALL | E_STRICT & ~E_NOTICE = 2047
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    stats:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    default_module:         utente
    default_action:         index
#
#    error_404_module:       default
#    error_404_action:       error404
#
    login_module:           login
    login_action:           index
#
#    module_disabled_module: default
#    module_disabled_action: disabled
#
    secure_module:          login
    secure_action:          secure
#
#    unavailable_module:     default
#    unavailable_action:     unavailable
#
  .settings:
#    available:              true
#
#    path_info_array:        SERVER
#    path_info_key:          PATH_INFO
#
#    url_format:             PATH
#
    use_database:           true
#
    use_security:           true
#
#    compressed:             true
#
#    tidy:                   true
#
#    i18n:                   false
#
#    timeout:                1800
#
#    suffix:                 .
#
    standard_helpers:       [Partial, Cache, Form, Date, Number, I18N, Javascript, Object]
#
#    max_forwards:           5
#
#    web_debug:              false
#
#    cache:                  false
#    default_cache_lifetime: 86400
#
#    no_script_name:         true
#
#    stats:                  false
#
#    # E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR = 337
#    error_reporting:        337
#
#    rich_text_js_dir:       js/tiny_mce
#
#    safe_slot:              true
#
#    use_flash:              true
#
#    enabled_modules:        [default]
#
#    strip_comments:         false
#
#    etag:                   true
#
#    validation_error_prefix:    ' &darr;&nbsp;'
#    validation_error_suffix:    ' &nbsp;&darr;'
#    validation_error_class:     form_error
#    validation_error_id_prefix: error_for_

 #   rich_text_fck_js_dir:  js/FCKeditor    
 #   rich_text_fck_base_dir:js/FCKeditor