default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        PIM On-line
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    []

  javascripts:    [prototype/prototype]

  has_layout:     true
  layout:         layout

  slots:          {}

  use_default_slots: true
