autoload:
  idLibrary:
    name: idLibrary
    ext: .class.php
    path: %SF_PLUGINS_DIR%/idLibrary/lib/test
    
  DomPDF:
    name:		  DomPdf
    ext: .cls.php
    path: %SF_APP_DIR%/lib/dompdf/include
