# default rules

fatture_acquisto:
  url: /fatture_acquisto
  param: {module: invoice, action: index, type: 2}
  
fatture_acquisto_create:
  url: /fatture_acquisto/create
  param: {module: invoice, action: create, type: 2}
  
fornitori:
  url: /fornitori
  param: {module: contact, action: index, type: 2}

fornitori_create:
  url: /fornitori/create
  param: {module: contact, action: create, type: 2}

statistiche:
  url: /statistiche
  param: { module: stats, action: index }

statistiche_mod:
  url: /statistiche/:action/*
  param: { module: stats }

contatti:
  url: /content/contatti
  param: {module: sito, action: contatti}

pagina:
  url:   /content/:titolo
  param: { module: sito, action: permalink }

homepage:
  url:   /
  param: { module: main, action: index}

default_index:
  url:   /:module
  param: { action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default:
  url:   /:module/:action/*

popular_tags:
  url:   /popular_tags
  param: { module: tag, action: popular }
