# default rules

user_edit:
  url: profile
  param: {module: utente, action: edit}

preferences:
  url: preferences
  param: {module: impostazione, action: index}

logout:
  url: logout
  param: {module: login, action: logout}

invoice:
  url: invoices
  param: {module: fattura, action: index}

invoice_create:
  url: invoices/new
  param: {module: fattura, action: create}

invoice_create_for_client:
  url: invoices/new/:id_cliente
  param: {module: fattura, action: create}

cashflow:
  url: cashflow
  param: {module: cashflow, action: index}

contact_show:
  url: contact/show/:id
  param: {module: contact, action: show}
  
contact_edit:
  url: contact/edit/:id
  param: {module: contact, action: edit}

contact_delete:
  url: contact/delete/:id
  param: {module: contact, action: delete}

document_purchase_create:
  url: cashflow/create/document/purchase
  param: {module: cashflow, action: create, type: 4}

document_sales_create:
  url: cashflow/create/document/sales
  param: {module: cashflow, action: create, type: 3}

fatture_acquisto:
  url: /fatture_acquisto
  param: {module: invoice, action: index, type: 2}

fatture_acquisto_create:
  url: /fatture_acquisto/create
  param: {module: invoice, action: create, type: 2}

customer:
  url: /clienti
  param: {module: contact, action: index, type: 1}

customer_create:
  url: /clienti/create
  param: {module: contact, action: create, type: 1}

provider:
  url: /fornitori
  param: {module: contact, action: index, type: 2}

provider_create:
  url: /fornitori/create
  param: {module: contact, action: create, type: 2}

statistiche:
  url: /statistiche
  param: { module: stats, action: index }

statistiche_mod:
  url: /statistiche/:action/*
  param: { module: stats }

contatti:
  url: /content/contatti
  param: {module: sito, action: contatti}

pagina:
  url:   /content/:titolo
  param: { module: sito, action: permalink }

homepage:
  url:   /
  param: { module: main, action: index}

default_index:
  url:   /:module
  param: { action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default:
  url:   /:module/:action/*

popular_tags:
  url:   /popular_tags
  param: { module: tag, action: popular }
