default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        Personal Invoice Manager
    robots:       index, follow
    description:  personal invoice manager
    keywords:     personal, invoice, manager
    language:     it

  stylesheets:    [main, pmi, menu]

  javascripts:    [prototype/prototype]

  has_layout:     on
  layout:         layout

  slots:          {}
  
  #SideBar Options
  components:
    topbar:  [main, topBar]
    sidebar: [main, sideBar]
    breadcrumps: [main, bread]
    demoAlert: [utente, demoAlert]
    giorniRest: [utente, giorniRimanenti]
    updateProfile: [main, updateProfile]
    adsense: [sito, adsense]
    demoScaduto: [main, demoScaduto]

