default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        Billify - simplify your business management
    robots:       index, follow
    description:  php, invoice, account
    keywords:     php, invoice, account
    language:     it

  stylesheets:    [impress/reset, impress/main, impress/style ]

  javascripts:    []

  has_layout:     true
  layout:         layout

  slots:          {}

  #SideBar Options
  components:
    sidebar: [main, sideBar]
    breadcrumps: [main, bread]
    demoAlert: [utente, demoAlert]
    giorniRest: [utente, giorniRimanenti]
    updateProfile: [main, updateProfile]
    adsense: [sito, adsense]
    demoScaduto: [main, demoScaduto]

