listFilterSuccess:
  has_layout: false

listAgainSuccess:
  has_layout: false

addTagSuccess:
  has_layout: false

tagAutocompleteSuccess:
  has_layout: false
  
deleteTagSuccess:
  has_layout: false
  
exportSuccess:
  has_layout: false

exportError:
  has_layout: false
  
listSuccess:
  components:
     breadcrumps: [fattura, breadList]

tagsSuccess:
  components:
     breadcrumps: [fattura, breadTags]
     
showSuccess:
  components:
     breadcrumps: [fattura, breadShow]

createSuccess:
  components:
    breadcrumps: [fattura, breadEdit]
    
editSuccess:
  components:
     breadcrumps: [fattura, breadEdit]
     
all:
  has_layout: true
  components:
       topbar: [main, topBar]
       