generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Pagina
    theme:            default
    
    list:
      title: Lista Pagine
      display: [id, titolo]
      
    edit:
      title: Modifica Pagina	
      fields: 
        titolo: {params: size=90}
        corpo: {params: size=90x30}
