default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [impress/reset, impress/style-website, impress/main-website, jquery.lightbox-0.5.css]

  javascripts:    [jquery, jquery.lightbox-0.5.min.js]

  has_layout:     true
  layout:         website
