dev:
  propel:
    param:
      classname: DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=demo_billify;host=localhost
      username:   demo_billify
      password:   demo
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
