dev:
  propel:
    param:
      classname: DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

prod:
  propel:
    param:
      username:   ideato
      password:   ideato123qwe

vetrina:
  propel:
    param:
      dsn:        mysql:dbname=demo_billify;host=localhost
      username:   demo_billify
      password:   billify

all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=billify;host=localhost
      username:   billify
      password:   billify
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
