dev:
  propel:
    param:
      classname: DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=billify_test;host=localhost

prod:
  propel:
    param:
      username:   ideato
      password:   ideato123qwe
      
all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=billify;host=localhost
      username:   billify
      password:   billify
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
