editSuccess:
  components:
    breadcrumps: [modipagamento, editBread]
    
createSuccess:
  components:
    breadcrumps: [modipagamento, createBread]
    
listSuccess:
  components:
    breadcrumps: [modipagamento, bread]