create:
  is_secure: false

register:
  is_secure: false

antispam:
  is_secure: false

askcode:
  is_secure: false

codesend:
  is_secure: false

forgetpassword:
  is_secure: false

sendpassword:
  is_secure: false

all:
  is_secure: true