generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Utente
    theme:            default
    
    fields:
      id_invitation_code: 	{name: Invito}
      data_attivazione: 	{name: Data Attivazione, params: date_format='dd/MM/yyyy'}
      data_rinnovo: 		{name: Data Rinnovo, params: date_format='dd/MM/yyyy'}
      nb_clienti: 			{name: N&ordm; Clienti}
      nb_fatture: 			{name: N&ordm; Fatture}
      sconto_label:			{name: Sconto}
      
    list:
      title: Lista Utenti Registrati
      display: 		[id, invito, nome, cognome, email, data_attivazione, data_rinnovo, stato, tipo, scontoLabel, nbClienti, nbFatture]
      filters:	[_tipo, _stato, nome, cognome, email]
      object_actions:
        _delete:
        changeStato: {name: Cambia Stato, action: changeStato}
        upgradeUtente:   { name: Aggiorna Tipo, action: upgradeUtente }
        sendUpgradeMail:   { name: Invia Mail di aggiornamento, action: sendUpgradeMail }
        sconto:   { name: Sconto, action: sconto }
      
    edit:
      title: Modifica Utente
      display: [nome, cognome, data_rinnovo, stato, tipo]
