all:
  has_layout: true
  components:
     topbar: [main, topBar]
     breadcrumps: [cliente, breadCliente]

showSuccess:
  components:
    breadcrumps: [cliente, breadShow]

editSuccess:
  components:
    breadcrumps: [cliente, breadEdit]
    
listSuccess:
  components:
     sidebar: [main, sideBar]
     
searchSuccess:
  has_layout: false
  
searchError:
  has_layout: false
  
anagraficaSuccess:
  has_layout: false
  
opzioniSuccess:
  has_layout: false
  
